language: python
python:
    - "3.7"

install:
    - pip install pytest-cov codecov
    - pip install .

script:
    - pytest -m "not slow" --cov=atlas
    - pytest -m "slow" --cov=atlas --cov-append

after_success:
    - codecov
